### ISSUE TITLE
User data table within the parser 

### ISSUE THREAD

**Issue by evnpwr** [lunarmodules/luaexpat#34]
It would be useful to have a user-definable data table attached to the parser, which would be visible to any callbacks called by that parser. This would help avoid the use of global variables. It seems like such a table could live in the `lxp_userdata` structure. 

I have no experience with c/lua interoperation, so I don't know how hard this would be, but I'm willing to try to implement this.

**Comment by tomasguisasola** [comment]
I think LuaExpat already offers that.  Have you tried to hang anything you need in the table used to define the callbacks in the creation of the parser (lxp.new)?

**Comment by evnpwr** [comment]
I'll try that. Thanks for the suggestion.

**Comment by evnpwr** [comment]
When I try to add a table to the table that gets sent to lxp.new  I see a `bad argument #-1 to 'new' (invalid option 'UserData')` error. My test code looks like this:
```
lxp = require"lxp"

callbacks = {
   StartElement = function (parser, name)
      print("start")
   end,
   EndElement = function (parser, name)
      print("end")
   end,
   UserData = { "test0", "test1" }
}

parser = lxp.new( callbacks )
```

**Comment by tomasguisasola** [comment]
You are right.  Sorry for the noise.

Anyway, you can share a table between the callbacks using Lua's upvalues:

```
lxp = require"lxp"

local shared_table = {}
callbacks = {
   StartElement = function (parser, name)
      print("start", shared_table)
      shared_table[name] = "anything you want to store"
   end,
   EndElement = function (parser, name)
      print("end", shared_table, shared_table[name])
   end,
}

parser = lxp.new( callbacks )
```

Note that both messages will print the same table address and the last print will show the string stored by the StartElement callback also.

Does it solve your problem?

**Comment by evnpwr** [comment]
Thanks for the suggestion. In your example if I made two different parsers they would both see the same shared_table, which isn't exactly what I want, but I've done some reading on Lua upvalues and I think they can be achieved to accmplish what I want.

I appreciate the advice.

**Comment by tomasguisasola** [comment]
I am sure you can do different sets of similar functions sharing particular data.  In Programming in Lua, by Roberto, I recommend the section about "Lexical Scoping".  The example about a counter seems to be what you want.

In other words, you can group the above code in a function that will produce the parser with a shared table, such as (untested code below):

```
lxp = require"lxp"

function new_parser ()
   local shared_table = {}
   local callbacks = {
      StartElement = function (parser, name)
         print("start", shared_table)
         shared_table[name] = "anything you want to store"
      end,
      EndElement = function (parser, name)
         print("end", shared_table, shared_table[name])
      end,
   }

   return lxp.new( callbacks )
end

first_parser = new_parser()
second_parser = new_parser()
```
