### ISSUE TITLE
CI tests against Expat 2.4.4 only while 2.6.2 is the latest release

### ISSUE THREAD

**Issue by hartwork** [lunarmodules/luaexpat#35]
Hi!

It would be nice if…

https://github.com/lunarmodules/luaexpat/blob/57f8966088abf8a00f8ab0bf88e1b6deea89c0bb/.github/workflows/unix_build.yml#L9-L15

…could maybe include both Expat versions 2.4.4 and the latest 2.6.2 via the matrix. Patching that would also show if CI is still green today. What do you think?

Best, Sebastian

**Comment by Tieske** [comment]
I think that would make sense.

**Comment by alerque** [comment]
I think the PR addressing this just mentioned the wrong issue number. See

**Comment by Tieske** [comment]
> I think the PR addressing this just mentioned the wrong issue number. See #37.

fixed.

@hartwork There would be no LuaExpat without your hard work on LibExpat. So thank you 🙏.
