### ISSUE TITLE
Please make new tag/release after 1.3.0

### ISSUE THREAD

**Issue by winterheart** [lunarmodules/luaexpat#9]
Since current repository is now considered official, please make new tag that distinguish new changes since 1.3.0 is made by old repo.

**Comment by Tieske** [comment]
A new [1.4 release is expected](https://github.com/lunarmodules/luaexpat/issues/5), which will harmonize the changes from the different forks.

The source archives in the other repo, as well as the packaged LuaRocks ones will not change.
